version: '3.8'

services:
  db:
    image: mysql:8.0       # Versão do MySQL
    container_name: backoffice_mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql   # Altere para uma senha segura
      MYSQL_DATABASE: mysql        # Nome da base de dados
      MYSQL_USER: raullino          # Nome de usuário para o backoffice
      MYSQL_PASSWORD: raullino  # Senha do usuário do backoffice
    ports:
      - "3306:3306"        # Exponha a porta 3306 para acesso externo
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backoffice_net

networks:
  backoffice_net:
    driver: bridge

volumes:
  mysql_data:
